-- ==============================================================================
-- SMART HEALTH AI - PRODUCTION SUPABASE SCHEMA
-- Includes Role-Based Access, Indexes, Triggers, and Storage integration
-- ==============================================================================

-- Create the main profiles table
CREATE TABLE profiles (
  id UUID REFERENCES auth.users ON DELETE CASCADE PRIMARY KEY,
  role TEXT DEFAULT 'patient' CHECK (role IN ('patient', 'doctor', 'family')),
  full_name TEXT,
  blood_group TEXT,
  allergies TEXT,
  critical_conditions TEXT,
  current_medications TEXT,
  primary_language TEXT DEFAULT 'English',
  
  -- Vitals
  age INTEGER,
  blood_pressure TEXT,
  heart_rate INTEGER,
  blood_sugar INTEGER,
  
  -- Family & Emergency Information
  father_name TEXT,
  mother_name TEXT,
  guardian_name TEXT,
  siblings TEXT,
  emergency_contacts TEXT,
  existing_diseases TEXT,
  insurance_details TEXT,
  hospital_preference TEXT,
  family_medical_history TEXT,
  organ_donor_status TEXT,
  emergency_notes TEXT,
  
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Create a table for medical records (AI analyzed)
CREATE TABLE medical_records (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users ON DELETE CASCADE,
  diagnosis TEXT,
  prescription TEXT,
  summary_ai TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Create a table for raw uploaded files (PDFs, Images, Lab Reports)
CREATE TABLE medical_documents (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  user_id UUID REFERENCES auth.users ON DELETE CASCADE,
  file_name TEXT NOT NULL,
  file_url TEXT NOT NULL,
  file_type TEXT,
  category TEXT DEFAULT 'Other', -- e.g., 'Lab Report', 'Prescription', 'X-Ray'
  uploaded_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Create family_members table 
CREATE TABLE family_members (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  owner_id UUID REFERENCES auth.users ON DELETE CASCADE,
  full_name TEXT NOT NULL,
  relationship TEXT,
  blood_group TEXT,
  allergies TEXT,
  critical_conditions TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- ==============================================================================
-- OPTIMIZATION: INDEXES
-- ==============================================================================
CREATE INDEX idx_medical_records_user_id ON medical_records(user_id);
CREATE INDEX idx_medical_documents_user_id ON medical_documents(user_id);
CREATE INDEX idx_family_members_owner_id ON family_members(owner_id);
CREATE INDEX idx_profiles_role ON profiles(role);

-- ==============================================================================
-- AUTOMATED TRIGGERS: update `updated_at` on modification
-- ==============================================================================
CREATE OR REPLACE FUNCTION trigger_set_timestamp()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER set_timestamp_profiles
BEFORE UPDATE ON profiles
FOR EACH ROW EXECUTE PROCEDURE trigger_set_timestamp();

CREATE TRIGGER set_timestamp_medical_records
BEFORE UPDATE ON medical_records
FOR EACH ROW EXECUTE PROCEDURE trigger_set_timestamp();

CREATE TRIGGER set_timestamp_family_members
BEFORE UPDATE ON family_members
FOR EACH ROW EXECUTE PROCEDURE trigger_set_timestamp();

-- ==============================================================================
-- SECURITY: ROW LEVEL SECURITY (RLS) POLICIES
-- ==============================================================================
ALTER TABLE profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE medical_records ENABLE ROW LEVEL SECURITY;
ALTER TABLE medical_documents ENABLE ROW LEVEL SECURITY;
ALTER TABLE family_members ENABLE ROW LEVEL SECURITY;

-- ----------------------------------------------------
-- PROFILES POLICIES
-- ----------------------------------------------------
CREATE POLICY "Users can see own profile" ON profiles FOR SELECT USING (auth.uid() = id);
CREATE POLICY "Users can update own profile" ON profiles FOR UPDATE USING (auth.uid() = id) WITH CHECK (auth.uid() = id);
CREATE POLICY "Users can insert own profile" ON profiles FOR INSERT WITH CHECK (auth.uid() = id);
-- PUBLIC EMERGENCY POLICY (Allows the QR scanner to see the profile)
CREATE POLICY "Public emergency profile access" ON profiles FOR SELECT USING (true);

-- ----------------------------------------------------
-- MEDICAL RECORDS POLICIES
-- ----------------------------------------------------
CREATE POLICY "Users can insert own medical records" ON medical_records FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users can view own medical records" ON medical_records FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Users can update own medical records" ON medical_records FOR UPDATE USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users can delete own medical records" ON medical_records FOR DELETE USING (auth.uid() = user_id);

-- ----------------------------------------------------
-- MEDICAL DOCUMENTS POLICIES
-- ----------------------------------------------------
CREATE POLICY "Users can insert own documents" ON medical_documents FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users can view own documents" ON medical_documents FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Users can delete own documents" ON medical_documents FOR DELETE USING (auth.uid() = user_id);

-- ----------------------------------------------------
-- FAMILY MEMBERS POLICIES
-- ----------------------------------------------------
CREATE POLICY "Users can insert family members" ON family_members FOR INSERT WITH CHECK (auth.uid() = owner_id);
CREATE POLICY "Users can view own family members" ON family_members FOR SELECT USING (auth.uid() = owner_id);
CREATE POLICY "Users can update own family members" ON family_members FOR UPDATE USING (auth.uid() = owner_id) WITH CHECK (auth.uid() = owner_id);
CREATE POLICY "Users can delete own family members" ON family_members FOR DELETE USING (auth.uid() = owner_id);